# Usando a imagem oficial do Nginx como base
FROM nginx:latest

# Copiar os arquivos do front-end para o diretório padrão do Nginx
COPY ./ /usr/share/nginx/html

# Expondo a porta 80 para que possamos acessar o front-end no navegador
EXPOSE 80